# Generated by Django 3.2 on 2023-05-15 15:13

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrousel',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('carr_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Key')),
                ('carr_title', models.CharField(max_length=50, verbose_name='titulo slider')),
                ('carr_downloadtext', models.TextField(verbose_name='texto de bajada')),
                ('carr_isbutton', models.IntegerField(choices=[(1, 'yes'), (2, 'no')], verbose_name='Tiene link?')),
                ('carr_linkbutton', models.TextField(blank=True, max_length=50, null=True, verbose_name='link del botón')),
                ('carr_buttontext', models.CharField(blank=True, max_length=10, null=True, verbose_name='texto del botón')),
                ('carr_nameimage', models.CharField(max_length=50, verbose_name='nombre imagen')),
                ('carr_image', models.ImageField(help_text='tamaño de la imagen 1920x1080, solo formatos .jpg|.png|.gif|.jpeg', upload_to='company_images/', verbose_name='subir imagen')),
                ('carr_isactive', models.IntegerField(choices=[(1, 'yes'), (2, 'no')], default=True, verbose_name='Slider activo')),
            ],
            options={
                'verbose_name_plural': 'El carrusel',
                'db_table': 'web_carrousel',
                'ordering': ['carr_id'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('com_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Key')),
                ('com_namecompany', models.CharField(max_length=100, verbose_name='nombre compañia')),
                ('com_sitename', models.CharField(max_length=100, verbose_name='nombre del sitio')),
                ('com_nameimagecompany', models.CharField(max_length=100, verbose_name='nombre imagen compañia')),
                ('com_imagecompany', models.ImageField(help_text='solo formatos .jpg|.png|.gif|.jpeg', upload_to='company_images/', verbose_name='subir imagen')),
                ('com_nameimagecompanyicon', models.CharField(max_length=100, verbose_name='nombre icono imagen compañia')),
                ('com_imagecompanyicon', models.ImageField(help_text='solo formatos .jpg|.png|.gif|.jpeg', upload_to='company_images/', verbose_name='subir imagen icon')),
                ('com_title', models.CharField(max_length=150, verbose_name='title del home')),
                ('com_address', models.CharField(help_text='ej: lourdes 1012, Quinta Normal, Santiago', max_length=255, verbose_name='dirección empresa')),
                ('com_phone', models.CharField(help_text='puede ir mas de uno seguido de un guión (-)', max_length=150, verbose_name='fono empresa')),
                ('com_mail', models.CharField(max_length=150, verbose_name='mail empresa')),
                ('com_textfooter', models.TextField(verbose_name='texto footer')),
            ],
            options={
                'verbose_name_plural': 'Las empresas',
                'db_table': 'web_company',
                'ordering': ['com_id'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('me_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Key')),
                ('me_name', models.CharField(max_length=100, verbose_name='nombre menu')),
                ('me_hasasearchengine', models.IntegerField(choices=[(1, 'yes'), (2, 'no')], default=2, verbose_name='tiene buscador?')),
                ('me_isactive', models.IntegerField(choices=[(1, 'yes'), (2, 'no')], default=1, verbose_name='Menu activo')),
            ],
            options={
                'verbose_name': 'Menú',
                'db_table': 'web_menu',
                'ordering': ['me_id'],
            },
        ),
        migrations.CreateModel(
            name='OtherLinks',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('ol_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Key')),
                ('ol_name', models.CharField(max_length=100, verbose_name='nombre link')),
                ('ol_link', models.TextField(max_length=150, verbose_name='link del item')),
                ('ol_order', models.IntegerField(verbose_name='posición del link')),
                ('ol_active', models.IntegerField(choices=[(1, 'yes'), (2, 'no')], default=1, verbose_name='link activo')),
            ],
            options={
                'verbose_name_plural': 'Otros links',
                'db_table': 'web_other_links',
                'ordering': ['ol_id'],
            },
        ),
        migrations.CreateModel(
            name='Plugins',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('plu_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Key')),
                ('plu_elementname', models.CharField(max_length=100, verbose_name='nombre del elemento')),
                ('plu_icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='icono del elemento')),
                ('plu_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='título del elemento')),
                ('plu_text', models.TextField(blank=True, null=True, verbose_name='texto')),
                ('plu_isbox', models.IntegerField(choices=[(1, 'yes'), (2, 'no')], default=2, verbose_name='tiene recuadro')),
                ('plu_linkactive', models.IntegerField(choices=[(1, 'yes'), (2, 'no')], default=1, verbose_name='link activo')),
                ('plu_link', models.TextField(blank=True, null=True, verbose_name='link del elemento')),
                ('plu_image', models.ImageField(blank=True, help_text='tamaño de la imagen 1920x1080, solo formatos .jpg|.png|.gif|.jpeg', null=True, upload_to='company_images/', verbose_name='subir imagen')),
                ('plu_active', models.IntegerField(choices=[(1, 'yes'), (2, 'no')], default=1, verbose_name='plugin activo')),
            ],
            options={
                'verbose_name_plural': 'Plugins',
                'db_table': 'web_plugins',
                'ordering': ['plu_id'],
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('sn_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Key')),
                ('sn_name', models.CharField(max_length=100, verbose_name='nombre red')),
                ('sn_icon', models.IntegerField(choices=[(1, 'fab fa-twitter fw-normal'), (2, 'fab fa-facebook-f fw-normal'), (3, 'fab fa-linkedin-in fw-normal'), (4, 'fab fa-instagram fw-normal'), (5, 'fab fa-youtube fw-normal')], verbose_name='icon red')),
                ('sn_link', models.TextField(verbose_name='link red')),
            ],
            options={
                'verbose_name_plural': 'Redes Sociales',
                'db_table': 'web_social_network',
                'ordering': ['sn_id'],
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('it_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Key')),
                ('it_name', models.CharField(max_length=100, verbose_name='nombre item')),
                ('it_link', models.TextField(max_length=150, verbose_name='link del item')),
                ('it_pagetype', models.IntegerField(blank=True, choices=[(1, 'Home'), (2, 'About'), (3, 'WhyChooseUs'), (4, 'OurServices'), (5, 'Contact')], null=True, verbose_name='tipo de página')),
                ('it_order', models.IntegerField(verbose_name='posición del item')),
                ('it_lincactive', models.CharField(default='active', max_length=10, verbose_name='link activo')),
                ('it_active', models.IntegerField(choices=[(1, 'yes'), (2, 'no')], default=1, verbose_name='item activo')),
                ('menu', models.ForeignKey(db_column='it_menu_id', on_delete=django.db.models.deletion.PROTECT, to='web.menu', verbose_name='Menu')),
            ],
            options={
                'verbose_name_plural': 'Items',
                'db_table': 'web_items',
                'ordering': ['it_id'],
            },
        ),
        migrations.CreateModel(
            name='BlockHome',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('bh_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Key')),
                ('bh_name', models.CharField(help_text='es el tipo de elemento que se verá en la página', max_length=100, verbose_name='nombre bloque')),
                ('bh_title', models.CharField(max_length=100, verbose_name='titulo del bloque')),
                ('bh_order', models.IntegerField(verbose_name='posición del bloque')),
                ('bh_image', models.ImageField(blank=True, help_text='tamaño de la imagen 1920x1080, solo formatos .jpg|.png|.gif|.jpeg', null=True, upload_to='company_images/', verbose_name='subir imagen')),
                ('bh_html', ckeditor.fields.RichTextField(blank=True, help_text='Ingrese el texto utilizando CKEditor.', null=True, verbose_name='HTML o texto para el bloque')),
                ('bh_defaultpage', models.IntegerField(blank=True, choices=[(1, 'About'), (2, 'WhyChooseUs'), (3, 'OurServices'), (4, 'Contact'), (100, 'FactStart')], null=True, verbose_name='página por defecto')),
                ('bh_active', models.IntegerField(choices=[(1, 'yes'), (2, 'no')], default=1, verbose_name='bloque activo')),
                ('plugins', models.ManyToManyField(blank=True, db_column='bh_plugins_id', to='web.Plugins')),
            ],
            options={
                'db_table': 'web_block_home',
                'ordering': ['bh_id'],
            },
        ),
    ]
